In [1]:
import pandas as pd
from IPython.display import display

# tsv 파일을 DataFrame으로 읽기
user = pd.read_csv('Adressa_5w/user.tsv', sep='\t', names=['User', 'History', 'Train', 'Test'])
user_raw = pd.read_csv('Adressa_5w/user(raw).tsv', sep='\t',  names=['User', 'History', 'Train', 'Test'])

history_news = pd.read_csv('Adressa_5w/history/news.tsv', sep='\t',  names=['News ID', 'Category', 'Sub-Category', 'Title', 'Body', 'ID', 'Publish', 'Click time history'])

train_news = pd.read_csv('Adressa_5w/train/news.tsv', sep='\t', names=['News ID', 'Category', 'Sub-Category', 'Title', 'Body', 'ID', 'Publish', 'Click time history'])
# train_behaviors = pd.read_csv('Adressa_5w/train/behaviors.tsv', sep='\t', names=['User ID', 'Click time', 'Click history', 'click'], errors='replace' )
with open('Adressa_5w/train/behaviors.tsv', 'r', encoding='utf-8', errors='replace') as file:
    train_behaviors = pd.read_csv(file, sep='\t', names=['User ID', 'Click time', 'Click history', 'click'])

test_news = pd.read_csv('Adressa_5w/test/news.tsv', sep='\t', names=['News ID', 'Category', 'Sub-Category', 'Title', 'Body', 'ID', 'Publish', 'Click time history'])
# test_behaviors = pd.read_csv('Adressa_5w/test/behaviors.tsv', sep='\t', names=['User ID', 'Click time', 'Click history', 'click'], errors='replace' )
with open('Adressa_5w/test/behaviors.tsv', 'r', encoding='utf-8', errors='replace') as file:
    test_behaviors = pd.read_csv(file, sep='\t', names=['User ID', 'Click time', 'Click history', 'click'])



C:\Users\hyunwoo\AppData\Local\Temp\ipykernel_25400\4024038772.py:6: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  user_raw = pd.read_csv('Adressa_5w/user(raw).tsv', sep='\t',  names=['User', 'History', 'Train', 'Test'])
C:\Users\hyunwoo\AppData\Local\Temp\ipykernel_25400\4024038772.py:13: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  train_behaviors = pd.read_csv(file, sep='\t', names=['User ID', 'Click time', 'Click history', 'click'])


In [2]:
user

User                                            History  \
0             U1  N1,2017-01-15 07:27:55,2017-01-15 08:00:03;N84...   
1             U2  N2,2017-01-14 14:26:01,2017-01-15 08:00:03;N24...   
2             U3  N3,2017-01-14 22:42:55,2017-01-15 08:00:03;N57...   
3             U7  N7,2017-01-14 21:29:43,2017-01-15 08:00:06;N25...   
4             U8  N8,2017-01-14 12:33:47,2017-01-15 08:00:06;N35...   
...          ...                                                ...   
315182  U1554690                                                NaN   
315183  U1554749                                                NaN   
315184  U1555002                                                NaN   
315185  U1555055                                                NaN   
315186  U1555073                                                NaN   

                                                    Train  \
0                                                     NaN   
1       N21013,2017-02-05 16:11:27,2017-02-06 02:12:29...   
2       N20781,2017-02-04 18:03:40,2017-02-05 12:47:45...   
3                                                     NaN   
4       N21357,2017-02-06 19:23:20,2017-02-07 06:15:17...   
...                                                   ...   
315182                                                NaN   
315183                                                NaN   
315184                                                NaN   
315185                                                NaN   
315186                                                NaN   

                                                     Test  
0                                                     NaN  
1       N22972,2017-02-12 10:14:41,2017-02-12 20:55:24...  
2       N23024,2017-02-12 16:24:32,2017-02-13 03:22:56...  
3                                                     NaN  
4       N23139,2017-02-13 05:03:29,2017-02-13 16:05:20...  
...                                                   ...  
315182  N24390,2017-02-18 21:08:33,2017-02-19 07:18:21...  
315183  N23995,2017-02-16 20:45:33,2017-02-19 07:21:29...  
315184  N5990,2008-10-24 12:12:19,2017-02-19 07:33:22;...  
315185  N24149,2017-02-17 19:11:53,2017-02-19 07:36:07...  
315186  N5357,2014-05-17 06:24:39,2017-02-19 07:37:25;...  

[315187 rows x 4 columns]

In [3]:
train_news

News ID   Category Sub-Category  \
0     N20773    nyheter     utenriks   
1     N20769   100sport  vintersport   
2     N20781   100sport      fotball   
3     N20828   100sport    ballsport   
4     N20845      pluss      nyheter   
...      ...        ...          ...   
7541   N3275     kultur   festivaler   
7542  N15650      pluss      okonomi   
7543   N9393  forbruker         hjem   
7544  N11802    nyheter  moreromsdal   
7545  N19893      pluss      nyheter   

                                               Title  \
0         Trump raser mot skroting av innreiseforbud   
1     Boblebad med denne jenta snudde Northugs humør   
2              Europatesten går uten Helland for RBK   
3      Derfor ble gulljenta Waade benket hele kampen   
4             - Alle forskere er ikke Frank Aarebrot   
...                                              ...   
7541                       Kjeften full av Bamsemums   
7542                   Har spesialisert seg på wraps   
7543                    Derfor får du sot på veggene   
7544               Er du Joker-millionæren fra Aure?   
7545      Fylkespolitikerne enige om ny godsterminal   

                                                   Body  \
0     Saken oppdateres. - Meningen til denne såkalte...   
1     Saken oppdateres. LYGNA: Etter å ha vært total...   
2     Saken oppdateres. – Jeg kunne vært feit og ove...   
3     Saken oppdateres. Byåsen – Bietigheim: 23–28 (...   
4     Professoren legger ikke skjul på at han synes ...   
...                                                 ...   
7541  Onsdagens UKA-utfordring til studentene på Glø...   
7542  Saken oppdateres. Erdal «Eddy» Polat (38) bruk...   
7543  Saken oppdateres. Etter hvert som kulden sette...   
7544  Saken oppdateres. Ifølge Norsk Tipping bor det...   
7545  - Det er flott at vi har blitt enige, men det ...   

                                            ID              Publish  \
0     de63c5320a310c0ecf1c3e3111a21c027e92b4e7  2017-02-04 17:39:36   
1     2e7b9b5e245744f06d7815dec6586d9787e70d11  2017-02-04 17:21:26   
2     bc5544dea71aaf336e5be277862ce79c76f7d6a7  2017-02-04 18:03:40   
3     3064d2a747bf1c9d1a67c4bc2a23b985b69b6581  2017-02-04 20:38:05   
4     92eb234635d418db5cfa66ea790ad7ceb465b8c8  2017-02-04 21:31:13   
...                                        ...                  ...   
7541  248a3f5a52e23bbf8b02bf2273516308ca18dc4b  2009-10-07 16:22:56   
7542  dc5c0f33f86147f3f1b851e1017b08c803eeda0b  2015-04-13 05:39:48   
7543  2410bfbea36e3d669a257cb6696e763d56ce343d  2014-11-11 12:52:47   
7544  4facdc4a2f572a5b07cca71d359c325749c37d3a  2016-11-20 08:41:42   
7545  933a7cbef5b535d51be16aef430d8a2c10d2eab7  2016-06-17 14:29:31   

                                     Click time history  
0     2017-02-05 08:00:02,2017-02-05 08:00:45,2017-0...  
1     2017-02-05 08:00:02,2017-02-05 08:00:03,2017-0...  
2     2017-02-05 08:00:03,2017-02-05 08:00:04,2017-0...  
3     2017-02-05 08:00:04,2017-02-05 08:00:07,2017-0...  
4     2017-02-05 08:00:04,2017-02-05 08:00:48,2017-0...  
...                                                 ...  
7541                                2017-02-12 07:49:04  
7542                                2017-02-12 07:50:43  
7543                                2017-02-12 07:51:09  
7544                                2017-02-12 07:51:51  
7545                                2017-02-12 07:52:54  

[7546 rows x 8 columns]

In [4]:
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from dataset import BaseDataset
import torch
import torch.nn as nn
import torch.nn.functional as F
import time
import numpy as np
from config import model_name
from tqdm import tqdm
import os
from pathlib import Path
# from evaluate import evaluate
import importlib
import datetime
import copy

try:
    Model = getattr(importlib.import_module(f"model.{model_name}"), model_name)
    config = getattr(importlib.import_module('config'), f"{model_name}Config")
except AttributeError:
    print(f"{model_name} not included!")
    exit()

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print('Model : ', Model)
print('config : ', config)
print('device : ', device)

Model :  <class 'model.LSTUR.LSTUR'>
config :  <class 'config.LSTURConfig'>
device :  cpu


In [5]:
class EarlyStopping:
    def __init__(self, patience=config.early_stop_patience):
        # 조기 종료 기준을 위한 patience 설정
        self.patience = patience
        self.counter = 0
        self.best_loss = np.Inf

    def __call__(self, val_loss):
        """
        성능이 개선되지 않으면 카운터를 증가시키고, 개선되었을 때는 카운터 초기화
        """
        if val_loss < self.best_loss:
            early_stop = False
            get_better = True
            self.counter = 0
            self.best_loss = val_loss
        else:
            get_better = False
            self.counter += 1
            if self.counter >= self.patience:
                early_stop = True
            else:
                early_stop = False
        if np.isnan(val_loss):
            early_stop = True
        return early_stop, get_better
    

def latest_checkpoint(directory):
    # 가장 최신 체크포인트 찾기 (특정 형식에 맞는 파일 찾기)
    if not os.path.exists(directory):
        return None
    all_checkpoints = {
        int(x.split('.')[0].split('-')[1]): x
        for x in os.listdir(directory)
        if (x.split('.')[0].split('-')[2] == config.candidate_type)
        if (x.split('.')[0].split('-')[3] == config.our_type)
        if (x.split('.')[0].split('-')[4] == config.loss_function)
    }
    if not all_checkpoints:
        return None
    return os.path.join(directory,
                        all_checkpoints[max(all_checkpoints.keys())])

def time_since(since):
    """
    Format elapsed time string.
    """
    now = time.time()
    elapsed_time = now - since
    return time.strftime("%H:%M:%S", time.gmtime(elapsed_time))

# 여기서부터 train함수

In [18]:
test_data = config.test_behaviors_file.replace('behaviors_','').split('.')[0]
test_data

'20_ltlive'

In [19]:
 # 결과 파일 이름 설정
result_file = f"./results/{config.data}/{model_name}/result_ep{config.num_epochs}_{config.candidate_type}_ns{config.negative_sampling_ratio}_{config.loss_function}_lifetime{config.lifetime}_testdata{test_data}_testfilter{config.test_filter}_his{config.history_type}_{config.numbering}"
result_file = f"{result_file}.txt"

result_file

'./results/Adressa_5w/LSTUR/result_ep1_rev_current_log_pop_ns4_CEL_lifetime36_testdata20_ltlive_testfilter0.05_hisrandom_105.txt'

In [16]:
try:
    pretrained_word_embedding = torch.from_numpy(
        np.load(f'{config.data}/train/pretrained_word_embedding.npy')).float()
except FileNotFoundError:
    pretrained_word_embedding = None

print(pretrained_word_embedding)

tensor([[ 0.0356, -0.9042,  0.6011,  ...,  0.6533, -0.2377,  1.7836],
        [ 0.0323, -0.1663, -0.1218,  ...,  0.6306,  0.5075,  0.0439],
        [-0.1985,  0.0248, -0.0491,  ...,  0.3963,  0.1454,  0.1223],
        ...,
        [-0.2491,  0.4837,  0.3012,  ...,  0.8467, -0.2863, -0.1597],
        [ 0.6082,  0.5353,  0.9582,  ...,  0.4557,  2.0003,  0.7711],
        [-0.1155, -0.0363,  0.3376,  ...,  0.2884,  0.1793, -0.0753]])


In [22]:
# Model class 사용
model = Model(config, pretrained_word_embedding).to(device)

model

LSTUR(
  (news_encoder): NewsEncoder(
    (word_embedding): Embedding(330900, 100, padding_idx=0)
    (category_embedding): Embedding(128, 300, padding_idx=0)
    (title_CNN): Conv2d(1, 300, kernel_size=(3, 100), stride=(1, 1), padding=(1, 0))
    (title_attention): AdditiveAttention(
      (linear): Linear(in_features=300, out_features=200, bias=True)
    )
  )
  (user_encoder): UserEncoder(
    (gru): GRU(900, 900)
  )
  (click_predictor): DotProductClickPredictor()
  (user_embedding): Embedding(229062, 900, padding_idx=0)
)

In [20]:
# 데이터셋 로드 및 DataLoader 설정
if (config.candidate_type == 'current_raw_value_pop') or (config.candidate_type == 'rev_current_raw_value_pop'):
    conf_mode = 'raw_value'
elif (config.candidate_type == 'current_sqrt_pop') or (config.candidate_type == 'rev_current_sqrt_pop'):
    conf_mode = 'sqrt'
elif (config.candidate_type == 'current_log_pop') or (config.candidate_type == 'rev_current_log_pop'):
    conf_mode = 'log'

conf_mode

'log'

In [14]:
# dataset = BaseDataset(f'{config.data}/train/{conf_mode}/'+config.behaviors_target_file,
#                           f'{config.data}/train/'+'news_parsed.tsv', f'{config.data}/train/roberta')

dataset = BaseDataset(f'{config.data}/train/{conf_mode}/behaviors_parsed_ns8_lt36.tsv',
                          f'{config.data}/train/'+'news_parsed.tsv', f'{config.data}/train/roberta')

print(f"Load training dataset with size {len(dataset)}.")

dataloader = iter(
    DataLoader(dataset,
                batch_size=config.batch_size,
                shuffle=True,
                num_workers=config.num_workers,
                drop_last=True,
                pin_memory=True))

Load training dataset with size 1543162.


In [18]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),
                                lr=config.learning_rate)
print(f"Loss function:{config.loss_function}, NS Type: {config.candidate_type}_{config.our_type}")

start_time = time.time()
loss_full = []
exhaustion_count = 0
step = 0
early_stopping = EarlyStopping()

Loss function:CEL, NS Type: rev_current_log_pop_onetype


In [19]:
# 체크포인트 및 결과 디렉토리 생성
checkpoint_dir = os.path.join('./checkpoint', config.data, model_name)
result_dir = os.path.join('./results', config.data, model_name)
Path(checkpoint_dir).mkdir(parents=True, exist_ok=True)
Path(result_dir).mkdir(parents=True, exist_ok=True)

In [20]:
# 가장 최근 체크포인트 불러오기 (없으면 None)
checkpoint_path = latest_checkpoint(checkpoint_dir)
checkpoint_path = None


In [21]:
epoch_result = []
if checkpoint_path is not None:
    # 체크포인트에서 파라미터 불러오기
    print(f"Load saved parameters in {checkpoint_path}")
    checkpoint = torch.load(checkpoint_path)
    early_stopping(checkpoint['early_stop_value'])
    step = checkpoint['step']
    exhaustion_count = checkpoint['exhaustion_count']
    epoch_result = [x.split(' ') for x in checkpoint['epoch_result'].split('\n')]
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    model.train()

## 연습

In [44]:
minibatch = next(dataloader)

In [ ]:
minibatch 

{'user': tensor([  9255,  98869,  10741,  16348, 192368, 176307,  20580,  38625,  55448,
         106551, 183242,  22713,    572,  60058,  23703,  13396, 168164,  65523,
          64426,  45201,  83384,  89908, 225386, 103642,    871,  57608, 164285,
          47827,  38786, 109305,  64710, 103758, 176746,  18285,  52922,  25000,
         200059,  58601,   7641,  25928,  61810, 142939,  40164,  55810, 201793,
          51797,  48789,   5829,  70938, 119243]),
 'clicked': [tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [45]:
minibatch["user"]

tensor([  9255,  98869,  10741,  16348, 192368, 176307,  20580,  38625,  55448,
        106551, 183242,  22713,    572,  60058,  23703,  13396, 168164,  65523,
         64426,  45201,  83384,  89908, 225386, 103642,    871,  57608, 164285,
         47827,  38786, 109305,  64710, 103758, 176746,  18285,  52922,  25000,
        200059,  58601,   7641,  25928,  61810, 142939,  40164,  55810, 201793,
         51797,  48789,   5829,  70938, 119243])

In [46]:
minibatch["clicked_news_length"]

tensor([ 3, 13, 50, 18,  2,  0, 50, 26, 11, 11, 17, 50,  5,  0, 26, 50,  0,  6,
        30, 13, 40, 24,  4, 13, 13, 26, 12, 12, 11, 12,  2, 16, 25, 50, 40,  4,
         2,  7, 45, 27, 31, 40, 20, 36, 16, 50, 50, 50, 22,  8])

In [47]:
minibatch["candidate_news"]

[{'category': tensor([ 5,  5,  9, 13, 13,  1,  1,  5,  5,  5,  5,  5,  1,  1,  1,  5,  1,  5,
           1,  5,  5,  5,  1,  1,  1,  1,  1,  5,  5,  5,  1,  5,  1,  9,  5,  1,
           9,  5,  1,  5,  5,  1,  5,  5,  5, 13,  9,  1,  1,  1]),
  'subcategory': tensor([16,  8,  5, 31, 31,  4,  4, 15,  8,  7,  8,  8,  4, 20, 20,  8,  4,  7,
          20, 16, 15,  6, 20, 20,  4, 20,  4,  8,  8,  8,  4,  8, 20,  5,  7, 20,
          11,  6, 20, 15, 15,  4,  6,  8,  8, 31, 13,  4,  4,  4]),
  'title': tensor([[  5011,   1535,   3763,   1601,    265,   1048,   1081,    358,  33213,
             1074,     47,  71187,      0,      0,      0,      0,      0,      0,
                0,      0],
          [   265,    293,     18,  10822,      7,    280,    106,     64,     75,
             4181,      0,      0,      0,      0,      0,      0,      0,      0,
                0,      0],
          [158067,    149, 313575, 306814,      0,      0,      0,      0,      0,
                0,      0,   

In [48]:
minibatch["clicked_news"]

[{'category': tensor([ 0,  0, 13,  0,  0,  0,  5,  0,  0,  0,  0,  1,  0,  0,  0,  5,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  9,  1,  0,  0]),
  'subcategory': tensor([ 0,  0, 31,  0,  0,  0,  6,  0,  0,  0,  0, 20,  0,  0,  0, 18,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  5, 20,  0,  0]),
  'title': tensor([[     0,      0,      0,      0,      0,      0,      0,      0,      0,
                0,      0,      0,      0,      0,      0,      0,      0,      0,
                0,      0],
          [     0,      0,      0,      0,      0,      0,      0,      0,      0,
                0,      0,      0,      0,      0,      0,      0,      0,      0,
                0,      0],
          [  5200,    604,  34361,  79443,      0,      0,      0,      0,      0,
                0,      0,   